#ifndef JMN_BERYLLIUM_INCLUDED
#  define JMN_BERYLLIUM_INCLUDED

namespace jmn
{

}

#endif // JMN_BERYLLIUM_INCLUDED

#ifdef __INTELLISENSE__
#  define JMN_BERYLLIUM_IMPLEMENTATION
#endif // __INTELLISENSE__

#ifdef JMN_BERYLLIUM_IMPLEMENTATION
#  ifndef JMN_BERYLLIUM_IMPLEMENTATED
#    define JMN_BERYLLIUM_IMPLEMENTATED

namespace jmn
{

}

#  endif // JMN_BERYLLIUM_IMPLEMENTATED
#endif // JMN_BERYLLIUM_IMPLEMENTATION
